CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE currencies (
        currency_code character varying(3) NOT NULL,
        name character varying(50),
        symbol character varying(10),
        decimal_places smallint NOT NULL,
        is_default boolean NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_currencies" PRIMARY KEY (currency_code)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE permissions (
        permission_id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(100) NOT NULL,
        description character varying(255),
        CONSTRAINT "PK_permissions" PRIMARY KEY (permission_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE subscription_plans (
        plan_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(50) NOT NULL,
        description character varying(255),
        price numeric NOT NULL,
        currency_code character varying(3) NOT NULL,
        billing_cycle character varying(20) NOT NULL,
        duration_days integer NOT NULL,
        max_branches integer NOT NULL,
        max_users integer NOT NULL,
        max_orders_per_month integer,
        features jsonb,
        is_active boolean NOT NULL,
        sort_order integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_subscription_plans" PRIMARY KEY (plan_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE super_admins (
        super_admin_id integer GENERATED BY DEFAULT AS IDENTITY,
        username character varying(50) NOT NULL,
        password_hash bytea NOT NULL,
        full_name character varying(100) NOT NULL,
        email character varying(100) NOT NULL,
        phone character varying(50),
        is_active boolean NOT NULL,
        last_login_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_super_admins" PRIMARY KEY (super_admin_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE companies (
        company_id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(100) NOT NULL,
        username character varying(50) NOT NULL,
        password_hash bytea NOT NULL,
        email character varying(100),
        phone character varying(50),
        address character varying(255),
        logo character varying(500),
        status character varying(20) NOT NULL,
        plan_id integer,
        plan_expiry_date timestamp with time zone,
        max_branches integer NOT NULL,
        max_users integer NOT NULL,
        trial_ends_at timestamp with time zone,
        notes character varying(500),
        created_at timestamp with time zone NOT NULL,
        created_by_super_admin_id integer,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_companies" PRIMARY KEY (company_id),
        CONSTRAINT "FK_companies_subscription_plans_plan_id" FOREIGN KEY (plan_id) REFERENCES subscription_plans (plan_id) ON DELETE SET NULL,
        CONSTRAINT "FK_companies_super_admins_created_by_super_admin_id" FOREIGN KEY (created_by_super_admin_id) REFERENCES super_admins (super_admin_id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE company_payments (
        payment_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        amount numeric NOT NULL,
        currency_code character varying(3) NOT NULL,
        payment_method character varying(50) NOT NULL,
        payment_reference character varying(100),
        payment_date timestamp with time zone NOT NULL,
        status character varying(20) NOT NULL,
        notes character varying(255),
        recorded_by_super_admin_id integer,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_company_payments" PRIMARY KEY (payment_id),
        CONSTRAINT "FK_company_payments_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_company_payments_super_admins_recorded_by_super_admin_id" FOREIGN KEY (recorded_by_super_admin_id) REFERENCES super_admins (super_admin_id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "InventoryItems" (
        "InventoryItemId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Code" character varying(50),
        "UnitOfMeasure" character varying(20) NOT NULL,
        "Category" character varying(50),
        "MinLevel" numeric(18,4) NOT NULL,
        "ReorderQty" numeric(18,4) NOT NULL,
        "CostMethod" character varying(20) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("InventoryItemId"),
        CONSTRAINT "FK_InventoryItems_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "LoyaltyTiers" (
        "LoyaltyTierId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "Name" character varying(50) NOT NULL,
        "MinTotalSpent" numeric(18,2) NOT NULL,
        "MinTotalPoints" numeric(18,2) NOT NULL,
        "TierDiscountPercent" numeric(5,2) NOT NULL,
        "Benefits" character varying(255),
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LoyaltyTiers" PRIMARY KEY ("LoyaltyTierId"),
        CONSTRAINT "FK_LoyaltyTiers_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE payment_methods (
        payment_method_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        name character varying(50) NOT NULL,
        type character varying(20) NOT NULL,
        requires_reference boolean NOT NULL,
        is_active boolean NOT NULL,
        sort_order integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_payment_methods" PRIMARY KEY (payment_method_id),
        CONSTRAINT "FK_payment_methods_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "Suppliers" (
        "SupplierId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "Name" character varying(100) NOT NULL,
        "ContactPerson" character varying(100),
        "Phone" character varying(50),
        "Email" character varying(100),
        "Address" character varying(255),
        "PaymentTerms" character varying(50),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Suppliers" PRIMARY KEY ("SupplierId"),
        CONSTRAINT "FK_Suppliers_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "AuditLogs" (
        "AuditLogId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "UserId" integer,
        "BranchId" integer,
        "ActionType" character varying(50) NOT NULL,
        "EntityName" character varying(50),
        "EntityId" integer,
        "Details" text,
        "IpAddress" character varying(50),
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("AuditLogId"),
        CONSTRAINT "FK_AuditLogs_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE branches (
        branch_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        name character varying(100) NOT NULL,
        code character varying(50),
        country character varying(100),
        city character varying(100),
        address character varying(255),
        phone character varying(50),
        default_currency_code character varying(3) NOT NULL,
        vat_percent numeric NOT NULL,
        service_charge_percent numeric NOT NULL,
        is_active boolean NOT NULL,
        deleted_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        updated_at timestamp with time zone,
        updated_by_user_id integer,
        CONSTRAINT "PK_branches" PRIMARY KEY (branch_id),
        CONSTRAINT "FK_branches_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_branches_currencies_default_currency_code" FOREIGN KEY (default_currency_code) REFERENCES currencies (currency_code) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE categories (
        category_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        branch_id integer,
        parent_category_id integer,
        name character varying(100) NOT NULL,
        name_ar character varying(100),
        sort_order integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_categories" PRIMARY KEY (category_id),
        CONSTRAINT "FK_categories_branches_branch_id" FOREIGN KEY (branch_id) REFERENCES branches (branch_id),
        CONSTRAINT "FK_categories_categories_parent_category_id" FOREIGN KEY (parent_category_id) REFERENCES categories (category_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_categories_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "CommissionPolicies" (
        "CommissionPolicyId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer,
        "SalesPercent" numeric(5,2) NOT NULL,
        "FixedPerInvoice" numeric(18,2) NOT NULL,
        "ApplyOnNetBeforeTax" boolean NOT NULL,
        "ExcludeDiscountedInvoices" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_CommissionPolicies" PRIMARY KEY ("CommissionPolicyId"),
        CONSTRAINT "FK_CommissionPolicies_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id),
        CONSTRAINT "FK_CommissionPolicies_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "Customers" (
        "CustomerId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "CustomerCode" character varying(50),
        "Name" character varying(100) NOT NULL,
        "Phone" character varying(50),
        "Email" character varying(100),
        "DefaultBranchId" integer,
        "DefaultCurrencyCode" character varying(3),
        "Notes" character varying(255),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId"),
        CONSTRAINT "FK_Customers_branches_DefaultBranchId" FOREIGN KEY ("DefaultBranchId") REFERENCES branches (branch_id),
        CONSTRAINT "FK_Customers_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "DeliveryZones" (
        "DeliveryZoneId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer NOT NULL,
        "ZoneName" character varying(100) NOT NULL,
        "Description" character varying(255),
        "MinOrderAmount" numeric(18,2),
        "BaseFee" numeric(18,2) NOT NULL,
        "ExtraFeePerKm" numeric(18,2),
        "MaxDistanceKm" numeric(18,2),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_DeliveryZones" PRIMARY KEY ("DeliveryZoneId"),
        CONSTRAINT "FK_DeliveryZones_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_DeliveryZones_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE kitchen_stations (
        kitchen_station_id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        name character varying(50) NOT NULL,
        color character varying(20),
        average_prep_time integer NOT NULL,
        display_order integer NOT NULL,
        alert_after_minutes integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_kitchen_stations" PRIMARY KEY (kitchen_station_id),
        CONSTRAINT "FK_kitchen_stations_branches_branch_id" FOREIGN KEY (branch_id) REFERENCES branches (branch_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "LoyaltySettings" (
        "LoyaltySettingsId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer,
        "PointsPerAmount" numeric(18,4) NOT NULL,
        "AmountUnit" numeric(18,4) NOT NULL,
        "EarnOnNetBeforeTax" boolean NOT NULL,
        "PointsRedeemValue" numeric(18,4) NOT NULL,
        "PointsExpiryMonths" integer,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LoyaltySettings" PRIMARY KEY ("LoyaltySettingsId"),
        CONSTRAINT "FK_LoyaltySettings_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id),
        CONSTRAINT "FK_LoyaltySettings_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE modifiers (
        modifier_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        branch_id integer,
        name character varying(100) NOT NULL,
        name_ar character varying(100),
        description character varying(255),
        extra_price numeric NOT NULL,
        currency_code character varying(3) NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_modifiers" PRIMARY KEY (modifier_id),
        CONSTRAINT "FK_modifiers_branches_branch_id" FOREIGN KEY (branch_id) REFERENCES branches (branch_id),
        CONSTRAINT "FK_modifiers_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "Printers" (
        "PrinterId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer NOT NULL,
        "Name" character varying(50) NOT NULL,
        "PrinterType" character varying(20) NOT NULL,
        "ConnectionType" character varying(20) NOT NULL,
        "ConnectionString" character varying(255),
        "PaperWidth" integer NOT NULL,
        "IsDefault" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Printers" PRIMARY KEY ("PrinterId"),
        CONSTRAINT "FK_Printers_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_Printers_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "ReceiptTemplates" (
        "ReceiptTemplateId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer,
        "TemplateType" character varying(20) NOT NULL,
        "Name" character varying(50) NOT NULL,
        "HeaderText" character varying(500),
        "FooterText" character varying(500),
        "ShowLogo" boolean NOT NULL,
        "ShowBarcode" boolean NOT NULL,
        "Language" character varying(10) NOT NULL,
        "IsDefault" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_ReceiptTemplates" PRIMARY KEY ("ReceiptTemplateId"),
        CONSTRAINT "FK_ReceiptTemplates_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id),
        CONSTRAINT "FK_ReceiptTemplates_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE restaurant_tables (
        table_id integer GENERATED BY DEFAULT AS IDENTITY,
        branch_id integer NOT NULL,
        table_name character varying(50) NOT NULL,
        zone character varying(50),
        capacity integer NOT NULL,
        status character varying(20) NOT NULL,
        floor_number integer NOT NULL,
        position_x integer,
        position_y integer,
        section_id integer,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_restaurant_tables" PRIMARY KEY (table_id),
        CONSTRAINT "FK_restaurant_tables_branches_branch_id" FOREIGN KEY (branch_id) REFERENCES branches (branch_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE roles (
        role_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer,
        branch_id integer,
        name character varying(50) NOT NULL,
        description character varying(255),
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_roles" PRIMARY KEY (role_id),
        CONSTRAINT "FK_roles_branches_branch_id" FOREIGN KEY (branch_id) REFERENCES branches (branch_id),
        CONSTRAINT "FK_roles_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE users (
        user_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        username character varying(50) NOT NULL,
        password_hash bytea NOT NULL,
        full_name character varying(100) NOT NULL,
        phone character varying(50),
        email character varying(100),
        default_branch_id integer,
        is_active boolean NOT NULL,
        deleted_at timestamp with time zone,
        last_login_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        created_by_user_id integer,
        updated_at timestamp with time zone,
        updated_by_user_id integer,
        CONSTRAINT "PK_users" PRIMARY KEY (user_id),
        CONSTRAINT "FK_users_branches_default_branch_id" FOREIGN KEY (default_branch_id) REFERENCES branches (branch_id) ON DELETE SET NULL,
        CONSTRAINT "FK_users_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "LoyaltyAccounts" (
        "LoyaltyAccountId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "PointsBalance" numeric(18,2) NOT NULL,
        "LoyaltyTierId" integer,
        "TierAssignedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_LoyaltyAccounts" PRIMARY KEY ("LoyaltyAccountId"),
        CONSTRAINT "FK_LoyaltyAccounts_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE CASCADE,
        CONSTRAINT "FK_LoyaltyAccounts_LoyaltyTiers_LoyaltyTierId" FOREIGN KEY ("LoyaltyTierId") REFERENCES "LoyaltyTiers" ("LoyaltyTierId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "CustomerAddresses" (
        "CustomerAddressId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "Label" character varying(50) NOT NULL,
        "AddressLine1" character varying(255) NOT NULL,
        "AddressLine2" character varying(255),
        "City" character varying(100) NOT NULL,
        "Area" character varying(100),
        "Latitude" numeric(9,6),
        "Longitude" numeric(9,6),
        "DeliveryZoneId" integer,
        "IsDefault" boolean NOT NULL,
        CONSTRAINT "PK_CustomerAddresses" PRIMARY KEY ("CustomerAddressId"),
        CONSTRAINT "FK_CustomerAddresses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE CASCADE,
        CONSTRAINT "FK_CustomerAddresses_DeliveryZones_DeliveryZoneId" FOREIGN KEY ("DeliveryZoneId") REFERENCES "DeliveryZones" ("DeliveryZoneId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE menu_items (
        menu_item_id integer GENERATED BY DEFAULT AS IDENTITY,
        company_id integer NOT NULL,
        branch_id integer,
        category_id integer NOT NULL,
        name character varying(100) NOT NULL,
        name_ar character varying(100),
        code character varying(50),
        description character varying(255),
        description_ar character varying(255),
        default_price numeric NOT NULL,
        currency_code character varying(3) NOT NULL,
        tax_included boolean NOT NULL,
        allow_sizes boolean NOT NULL,
        has_recipe boolean NOT NULL,
        kitchen_station_id integer,
        is_visible_online_menu boolean NOT NULL,
        item_commission_per_unit numeric,
        is_active boolean NOT NULL,
        image_url character varying(500),
        calories integer,
        prep_time_minutes integer,
        allergens character varying(255),
        is_available boolean NOT NULL,
        is_featured boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        CONSTRAINT "PK_menu_items" PRIMARY KEY (menu_item_id),
        CONSTRAINT "FK_menu_items_branches_branch_id" FOREIGN KEY (branch_id) REFERENCES branches (branch_id),
        CONSTRAINT "FK_menu_items_categories_category_id" FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_menu_items_companies_company_id" FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_menu_items_kitchen_stations_kitchen_station_id" FOREIGN KEY (kitchen_station_id) REFERENCES kitchen_stations (kitchen_station_id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "KitchenStationPrinters" (
        "KitchenStationPrinterId" integer GENERATED BY DEFAULT AS IDENTITY,
        "KitchenStationId" integer NOT NULL,
        "PrinterId" integer NOT NULL,
        CONSTRAINT "PK_KitchenStationPrinters" PRIMARY KEY ("KitchenStationPrinterId"),
        CONSTRAINT "FK_KitchenStationPrinters_Printers_PrinterId" FOREIGN KEY ("PrinterId") REFERENCES "Printers" ("PrinterId") ON DELETE RESTRICT,
        CONSTRAINT "FK_KitchenStationPrinters_kitchen_stations_KitchenStationId" FOREIGN KEY ("KitchenStationId") REFERENCES kitchen_stations (kitchen_station_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE role_permissions (
        role_permission_id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id integer NOT NULL,
        permission_id integer NOT NULL,
        CONSTRAINT "PK_role_permissions" PRIMARY KEY (role_permission_id),
        CONSTRAINT "FK_role_permissions_permissions_permission_id" FOREIGN KEY (permission_id) REFERENCES permissions (permission_id) ON DELETE CASCADE,
        CONSTRAINT "FK_role_permissions_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "Employees" (
        "EmployeeId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "UserId" integer,
        "BranchId" integer NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "Position" character varying(50) NOT NULL,
        "BaseSalary" numeric(18,2),
        "HireDate" timestamp with time zone,
        "Phone" character varying(50),
        "Email" character varying(100),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Employees" PRIMARY KEY ("EmployeeId"),
        CONSTRAINT "FK_Employees_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_Employees_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Employees_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "ExchangeRates" (
        "ExchangeRateId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BaseCurrencyCode" character varying(3) NOT NULL,
        "ForeignCurrencyCode" character varying(3) NOT NULL,
        "Rate" numeric(18,6) NOT NULL,
        "ValidFrom" timestamp with time zone NOT NULL,
        "ValidTo" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer,
        CONSTRAINT "PK_ExchangeRates" PRIMARY KEY ("ExchangeRateId"),
        CONSTRAINT "FK_ExchangeRates_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_ExchangeRates_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "GiftCards" (
        "GiftCardId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "GiftCardNumber" character varying(50) NOT NULL,
        "BranchIssuedId" integer NOT NULL,
        "IssueDate" timestamp with time zone NOT NULL,
        "CurrencyCode" character varying(3) NOT NULL,
        "InitialValue" numeric(18,2) NOT NULL,
        "CurrentBalance" numeric(18,2) NOT NULL,
        "ExpiryDate" timestamp with time zone,
        "Status" character varying(20) NOT NULL,
        "CustomerId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer,
        CONSTRAINT "PK_GiftCards" PRIMARY KEY ("GiftCardId"),
        CONSTRAINT "FK_GiftCards_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId"),
        CONSTRAINT "FK_GiftCards_branches_BranchIssuedId" FOREIGN KEY ("BranchIssuedId") REFERENCES branches (branch_id) ON DELETE CASCADE,
        CONSTRAINT "FK_GiftCards_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_GiftCards_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "Reservations" (
        "ReservationId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer NOT NULL,
        "CustomerId" integer,
        "CustomerName" character varying(100),
        "CustomerPhone" character varying(50),
        "ReservationDate" timestamp with time zone NOT NULL,
        "StartTime" interval NOT NULL,
        "DurationMinutes" integer NOT NULL,
        "PartySize" integer NOT NULL,
        "TableId" integer,
        "Status" character varying(20) NOT NULL,
        "Channel" character varying(20) NOT NULL,
        "Notes" character varying(255),
        "CreatedAt" timestamp with time zone NOT NULL,
        "CreatedByUserId" integer,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Reservations" PRIMARY KEY ("ReservationId"),
        CONSTRAINT "FK_Reservations_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId"),
        CONSTRAINT "FK_Reservations_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_Reservations_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Reservations_restaurant_tables_TableId" FOREIGN KEY ("TableId") REFERENCES restaurant_tables (table_id),
        CONSTRAINT "FK_Reservations_users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "SystemSettings" (
        "SettingId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "BranchId" integer,
        "SettingKey" character varying(100) NOT NULL,
        "SettingValue" text,
        "SettingType" character varying(20) NOT NULL,
        "Description" character varying(255),
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedByUserId" integer,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("SettingId"),
        CONSTRAINT "FK_SystemSettings_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id),
        CONSTRAINT "FK_SystemSettings_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_SystemSettings_users_UpdatedByUserId" FOREIGN KEY ("UpdatedByUserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE user_roles (
        user_role_id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        role_id integer NOT NULL,
        assigned_at timestamp with time zone NOT NULL,
        assigned_by_user_id integer,
        CONSTRAINT "PK_user_roles" PRIMARY KEY (user_role_id),
        CONSTRAINT "FK_user_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE CASCADE,
        CONSTRAINT "FK_user_roles_users_assigned_by_user_id" FOREIGN KEY (assigned_by_user_id) REFERENCES users (user_id),
        CONSTRAINT "FK_user_roles_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "LoyaltyTransactions" (
        "LoyaltyTransactionId" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoyaltyAccountId" integer NOT NULL,
        "TransactionDate" timestamp with time zone NOT NULL,
        "Type" character varying(20) NOT NULL,
        "PointsChange" numeric(18,2) NOT NULL,
        "PointsBefore" numeric(18,2) NOT NULL,
        "PointsAfter" numeric(18,2) NOT NULL,
        "OrderId" integer,
        "Notes" character varying(255),
        "UserId" integer,
        CONSTRAINT "PK_LoyaltyTransactions" PRIMARY KEY ("LoyaltyTransactionId"),
        CONSTRAINT "FK_LoyaltyTransactions_LoyaltyAccounts_LoyaltyAccountId" FOREIGN KEY ("LoyaltyAccountId") REFERENCES "LoyaltyAccounts" ("LoyaltyAccountId") ON DELETE CASCADE,
        CONSTRAINT "FK_LoyaltyTransactions_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE menu_item_modifiers (
        menu_item_modifier_id integer GENERATED BY DEFAULT AS IDENTITY,
        menu_item_id integer NOT NULL,
        modifier_id integer NOT NULL,
        is_required boolean NOT NULL,
        max_quantity integer,
        sort_order integer NOT NULL,
        CONSTRAINT "PK_menu_item_modifiers" PRIMARY KEY (menu_item_modifier_id),
        CONSTRAINT "FK_menu_item_modifiers_menu_items_menu_item_id" FOREIGN KEY (menu_item_id) REFERENCES menu_items (menu_item_id) ON DELETE CASCADE,
        CONSTRAINT "FK_menu_item_modifiers_modifiers_modifier_id" FOREIGN KEY (modifier_id) REFERENCES modifiers (modifier_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE menu_item_sizes (
        menu_item_size_id integer GENERATED BY DEFAULT AS IDENTITY,
        menu_item_id integer NOT NULL,
        size_name character varying(50) NOT NULL,
        price numeric NOT NULL,
        currency_code character varying(3) NOT NULL,
        cost numeric,
        CONSTRAINT "PK_menu_item_sizes" PRIMARY KEY (menu_item_size_id),
        CONSTRAINT "FK_menu_item_sizes_menu_items_menu_item_id" FOREIGN KEY (menu_item_id) REFERENCES menu_items (menu_item_id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "GiftCardTransactions" (
        "GiftCardTransactionId" integer GENERATED BY DEFAULT AS IDENTITY,
        "GiftCardId" integer NOT NULL,
        "TransactionDate" timestamp with time zone NOT NULL,
        "Type" character varying(20) NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "CurrencyCode" character varying(3) NOT NULL,
        "BalanceBefore" numeric(18,2) NOT NULL,
        "BalanceAfter" numeric(18,2) NOT NULL,
        "OrderId" integer,
        "UserId" integer,
        "Notes" character varying(255),
        CONSTRAINT "PK_GiftCardTransactions" PRIMARY KEY ("GiftCardTransactionId"),
        CONSTRAINT "FK_GiftCardTransactions_GiftCards_GiftCardId" FOREIGN KEY ("GiftCardId") REFERENCES "GiftCards" ("GiftCardId") ON DELETE CASCADE,
        CONSTRAINT "FK_GiftCardTransactions_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "ReservationDeposits" (
        "ReservationDepositId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ReservationId" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "CurrencyCode" character varying(3) NOT NULL,
        "Status" character varying(20) NOT NULL,
        "PaymentMethodId" integer,
        "PaidAt" timestamp with time zone,
        "RefundedAt" timestamp with time zone,
        "UserId" integer,
        CONSTRAINT "PK_ReservationDeposits" PRIMARY KEY ("ReservationDepositId"),
        CONSTRAINT "FK_ReservationDeposits_Reservations_ReservationId" FOREIGN KEY ("ReservationId") REFERENCES "Reservations" ("ReservationId") ON DELETE CASCADE,
        CONSTRAINT "FK_ReservationDeposits_payment_methods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES payment_methods (payment_method_id),
        CONSTRAINT "FK_ReservationDeposits_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (user_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "Recipes" (
        "RecipeId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" integer NOT NULL,
        "MenuItemId" integer NOT NULL,
        "MenuItemSizeId" integer,
        "YieldQuantity" numeric(18,4) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Recipes" PRIMARY KEY ("RecipeId"),
        CONSTRAINT "FK_Recipes_companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES companies (company_id) ON DELETE CASCADE,
        CONSTRAINT "FK_Recipes_menu_item_sizes_MenuItemSizeId" FOREIGN KEY ("MenuItemSizeId") REFERENCES menu_item_sizes (menu_item_size_id),
        CONSTRAINT "FK_Recipes_menu_items_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES menu_items (menu_item_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE TABLE "RecipeIngredients" (
        "RecipeIngredientId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RecipeId" integer NOT NULL,
        "InventoryItemId" integer NOT NULL,
        "QuantityPerYield" numeric(18,4) NOT NULL,
        CONSTRAINT "PK_RecipeIngredients" PRIMARY KEY ("RecipeIngredientId"),
        CONSTRAINT "FK_RecipeIngredients_InventoryItems_InventoryItemId" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("InventoryItemId") ON DELETE RESTRICT,
        CONSTRAINT "FK_RecipeIngredients_Recipes_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipes" ("RecipeId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_AuditLogs_BranchId" ON "AuditLogs" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_AuditLogs_CompanyId" ON "AuditLogs" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_branches_company_id_code" ON branches (company_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_branches_created_by_user_id" ON branches (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_branches_default_currency_code" ON branches (default_currency_code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_branches_updated_by_user_id" ON branches (updated_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_categories_branch_id" ON categories (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_categories_company_id" ON categories (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_categories_parent_category_id" ON categories (parent_category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_CommissionPolicies_BranchId" ON "CommissionPolicies" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_CommissionPolicies_CompanyId" ON "CommissionPolicies" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_companies_created_by_super_admin_id" ON companies (created_by_super_admin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_companies_plan_id" ON companies (plan_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_companies_username" ON companies (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_company_payments_company_id" ON company_payments (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_company_payments_recorded_by_super_admin_id" ON company_payments (recorded_by_super_admin_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_CustomerAddresses_CustomerId" ON "CustomerAddresses" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_CustomerAddresses_DeliveryZoneId" ON "CustomerAddresses" ("DeliveryZoneId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_Customers_CompanyId_CustomerCode" ON "Customers" ("CompanyId", "CustomerCode") WHERE [CustomerCode] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Customers_DefaultBranchId" ON "Customers" ("DefaultBranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_DeliveryZones_BranchId" ON "DeliveryZones" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_DeliveryZones_CompanyId" ON "DeliveryZones" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Employees_BranchId" ON "Employees" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Employees_CompanyId" ON "Employees" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Employees_UserId" ON "Employees" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_ExchangeRates_CompanyId" ON "ExchangeRates" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_ExchangeRates_CreatedByUserId" ON "ExchangeRates" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_GiftCards_BranchIssuedId" ON "GiftCards" ("BranchIssuedId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_GiftCards_CompanyId_GiftCardNumber" ON "GiftCards" ("CompanyId", "GiftCardNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_GiftCards_CreatedByUserId" ON "GiftCards" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_GiftCards_CustomerId" ON "GiftCards" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_GiftCardTransactions_GiftCardId" ON "GiftCardTransactions" ("GiftCardId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_GiftCardTransactions_UserId" ON "GiftCardTransactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_InventoryItems_CompanyId_Code" ON "InventoryItems" ("CompanyId", "Code") WHERE [Code] IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_kitchen_stations_branch_id" ON kitchen_stations (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_KitchenStationPrinters_KitchenStationId_PrinterId" ON "KitchenStationPrinters" ("KitchenStationId", "PrinterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_KitchenStationPrinters_PrinterId" ON "KitchenStationPrinters" ("PrinterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltyAccounts_CustomerId" ON "LoyaltyAccounts" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltyAccounts_LoyaltyTierId" ON "LoyaltyAccounts" ("LoyaltyTierId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltySettings_BranchId" ON "LoyaltySettings" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltySettings_CompanyId" ON "LoyaltySettings" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltyTiers_CompanyId" ON "LoyaltyTiers" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltyTransactions_LoyaltyAccountId" ON "LoyaltyTransactions" ("LoyaltyAccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_LoyaltyTransactions_UserId" ON "LoyaltyTransactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_item_modifiers_menu_item_id" ON menu_item_modifiers (menu_item_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_item_modifiers_modifier_id" ON menu_item_modifiers (modifier_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_item_sizes_menu_item_id" ON menu_item_sizes (menu_item_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_items_branch_id" ON menu_items (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_items_category_id" ON menu_items (category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_items_company_id" ON menu_items (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_menu_items_kitchen_station_id" ON menu_items (kitchen_station_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_modifiers_branch_id" ON modifiers (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_modifiers_company_id" ON modifiers (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_payment_methods_company_id" ON payment_methods (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Printers_BranchId" ON "Printers" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Printers_CompanyId" ON "Printers" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_ReceiptTemplates_BranchId" ON "ReceiptTemplates" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_ReceiptTemplates_CompanyId" ON "ReceiptTemplates" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_RecipeIngredients_InventoryItemId" ON "RecipeIngredients" ("InventoryItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_RecipeIngredients_RecipeId" ON "RecipeIngredients" ("RecipeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Recipes_CompanyId" ON "Recipes" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_Recipes_MenuItemId_MenuItemSizeId" ON "Recipes" ("MenuItemId", "MenuItemSizeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Recipes_MenuItemSizeId" ON "Recipes" ("MenuItemSizeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_ReservationDeposits_PaymentMethodId" ON "ReservationDeposits" ("PaymentMethodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_ReservationDeposits_ReservationId" ON "ReservationDeposits" ("ReservationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_ReservationDeposits_UserId" ON "ReservationDeposits" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Reservations_BranchId" ON "Reservations" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Reservations_CompanyId" ON "Reservations" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Reservations_CreatedByUserId" ON "Reservations" ("CreatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Reservations_CustomerId" ON "Reservations" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Reservations_TableId" ON "Reservations" ("TableId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_restaurant_tables_branch_id" ON restaurant_tables (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_role_permissions_permission_id" ON role_permissions (permission_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_role_permissions_role_id" ON role_permissions (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_roles_branch_id" ON roles (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_roles_company_id" ON roles (company_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_super_admins_username" ON super_admins (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_Suppliers_CompanyId" ON "Suppliers" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_SystemSettings_BranchId" ON "SystemSettings" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_SystemSettings_CompanyId_BranchId_SettingKey" ON "SystemSettings" ("CompanyId", "BranchId", "SettingKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_SystemSettings_UpdatedByUserId" ON "SystemSettings" ("UpdatedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_user_roles_assigned_by_user_id" ON user_roles (assigned_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_user_roles_user_id" ON user_roles (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE UNIQUE INDEX "IX_users_company_id_username" ON users (company_id, username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    CREATE INDEX "IX_users_default_branch_id" ON users (default_branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_AuditLogs_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches (branch_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    ALTER TABLE "AuditLogs" ADD CONSTRAINT "FK_AuditLogs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    ALTER TABLE branches ADD CONSTRAINT "FK_branches_users_created_by_user_id" FOREIGN KEY (created_by_user_id) REFERENCES users (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    ALTER TABLE branches ADD CONSTRAINT "FK_branches_users_updated_by_user_id" FOREIGN KEY (updated_by_user_id) REFERENCES users (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251207120138_AddNewCompanyModels') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251207120138_AddNewCompanyModels', '9.0.0');
    END IF;
END $EF$;
COMMIT;

